name: Bump version

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Bump patch version
        run: |
          git checkout master
          git version patch
          git commit -m "Automatically bump patch version on github release created" .
          git push
